services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: mistral
      POSTGRES_PASSWORD: mistral
      POSTGRES_DB: mistral_dev
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:

